# -*- coding: utf-8 -*-
"""DVA Assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1plDl2jZuzgU7zr6XOtyGK7lU00xdZf8z
"""

# ================================
# 1. ENVIRONMENT SETUP & IMPORTS
# ================================
!pip install -q transformers datasets

import re
import torch
import numpy as np
import pandas as pd
from datasets import load_dataset, Dataset
from sklearn.model_selection import train_test_split
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments

# ================================
# 2. DATASET LOADING
# ================================
dataset = load_dataset("hate_speech_offensive")

df = dataset['train'].to_pandas()

df['label'] = df['class'].map({
    0: "hate",
    1: "offensive",
    2: "normal"
})

df = df[['tweet','label']]
df.columns = ['text','label']

print(df['label'].value_counts())

df_balanced = df.groupby('label').apply(lambda x: x.sample(8000, random_state=42, replace=True)).reset_index(drop=True)

print(df_balanced['label'].value_counts())

# ================================
# 3. EXPLORATORY DATA ANALYSIS & VISUALIZATION
# ================================
print("Dataset Shape:", df.shape)
print("\nColumns:", df.columns)

print("\nSample Data:")
print(df.head())

print("\nClass Distribution:")
print(df['label'].value_counts())
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
sns.countplot(x='label', data=df, palette='viridis')
plt.title("Class Distribution of Labels")
plt.xlabel("Class")
plt.ylabel("Count")
plt.show()
df['text_length'] = df['text'].apply(len)

plt.figure(figsize=(6,4))
sns.histplot(df['text_length'], bins=50, kde=True)
plt.title("Tweet Length Distribution")
plt.xlabel("Length of Tweet")
plt.ylabel("Frequency")
plt.show()
from collections import Counter

all_words = " ".join(df['text']).split()
word_freq = Counter(all_words)

common_words = word_freq.most_common(20)

words = [w[0] for w in common_words]
counts = [w[1] for w in common_words]

plt.figure(figsize=(10,5))
sns.barplot(x=counts, y=words)
plt.title("Top 20 Most Common Words")
plt.xlabel("Frequency")
plt.ylabel("Words")
plt.show()

# ================================
# 4. DATA PREPROCESSING
# ================================
def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+|www\S+", "", text)
    text = re.sub(r"@\w+|#\w+", "", text)
    text = re.sub(r"[^\w\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df_balanced['clean_text'] = df_balanced['text'].apply(clean_text)

!pip install -q wordcloud

# ================================
# 5. WORD CLOUD VISUALIZATION
# ================================
from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Use a sample to avoid memory overload
sample_text = " ".join(df_balanced['clean_text'].sample(5000, random_state=42))

wordcloud = WordCloud(
    width=800,
    height=400,
    background_color='white'
).generate(sample_text)

plt.figure(figsize=(10,5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.title("Word Cloud of Tweets")
plt.show()

# 5.1 Class-wise Word Clouds
for label in df_balanced['label'].unique():
    text = " ".join(df_balanced[df_balanced['label']==label]['clean_text'].sample(3000))

    wc = WordCloud(width=800, height=400, background_color='white').generate(text)

    plt.figure(figsize=(8,4))
    plt.imshow(wc)
    plt.axis("off")
    plt.title(f"Word Cloud - {label}")
    plt.show()

# ================================
# 6. LABEL ENCODING
# ================================
label_map = {
    "normal":0,
    "offensive":1,
    "hate":2
}

df_balanced['label_id'] = df_balanced['label'].map(label_map)

# ================================
# 7. DATA BALANCING
# ================================
df_small = df_balanced.sample(20000, random_state=42)

# ================================
# 8. TOKENIZATION AND DATASET PREPARATION
# ================================
model_name = "xlm-roberta-base"

tokenizer = AutoTokenizer.from_pretrained(model_name)

dataset = Dataset.from_pandas(df_small[['clean_text','label_id']])

def tokenize(ex):
    return tokenizer(ex['clean_text'], truncation=True, padding='max_length', max_length=64)

dataset = dataset.map(tokenize, batched=True)
dataset = dataset.rename_column('label_id', 'labels') # Add this line to rename the column
dataset = dataset.train_test_split(test_size=0.1)

# ================================
# 9. MODEL INITIALIZATION AND LABEL CONFIGURATION
# ================================
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=3
)

model.config.id2label = {
    0: "normal",
    1: "offensive",
    2: "hate"
}

model.config.label2id = {
    "normal":0,
    "offensive":1,
    "hate":2
}

# ================================
# 10. MODEL TRAINING
# ================================
from transformers import DataCollatorWithPadding

training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    fp16=True,
    logging_steps=100,
    save_strategy="no"
)

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset['train'],
    eval_dataset=dataset['test'],
    data_collator=data_collator
)

trainer.train()

# ================================
# 11. PREDICTION FUNCTION
# ================================
def predict(text):
    model.eval()

    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model(**inputs)
        probs = torch.softmax(outputs.logits, dim=1)

    pred_id = torch.argmax(probs).item()

    print("Probabilities:", probs)
    return model.config.id2label[pred_id]

# ================================
# 12. TESTING & RESULTS
# ================================
print(predict("You are such an idiot"))
print(predict("I hate you"))
print(predict("Have a great day"))

!jupyter nbconvert --to script Assignment2.ipynb